export const  orderData = [
    {
      Order_ID: 1001,
      Customer_Name: "John Smith",
      Customer_Phone: "555-1234",
      Customer_Address: "123 Main St",
      Items: [
        {
          Item_Name: "Pepperoni Pizza",
          Item_Price: 10.99,
          Item_Type: "Food",
          Quantity: 1,
          Rating: "4",
          Total_Price: 10.99,
        },
        {
          Item_Name: "Garlic Bread",
          Item_Price: 5.99,
          Quantity: 2,
          Total_Price: 11.98,
        },
        {
          Item_Name: "Soft Drink",
          Item_Price: 2.49,
          Item_Type: "Beverage",
          Quantity: 1,
          Total_Price: 2.49,
        },
      ],
      Order_Type: "Online",
      Order_Status: "Delivered",
      Delivery_Person: "Sarah Johnson",
      Order_Placed_Time: "2024-05-08T11:00:00",
      Order_delivery_time: "2024-11-01T12:00:00",
      Delivery_Status: "Delivered",
      Customer_Rating: "4",
      Order_Date: "2024-10-11",
    },
    {
      Order_ID: 1002,
      Customer_Name: "Alice Johnson",
      Customer_Phone: "555-5678",
      Customer_Address: "456 Elm St",
      Items: [
        {
          Item_Name: "Cheeseburger",
          Item_Price: 8.99,
          Quantity: 2,
          Total_Price: 17.98,
        },
        {
          Item_Name: "French Fries",
          Item_Price: 3.99,
          Quantity: 1,
          Total_Price: 3.99,
        },
        {
          Item_Name: "Milkshake",
          Item_Price: 4.99,
          Quantity: 1,
          Total_Price: 4.99,
        },
      ],
      Order_Type: "Online",
      Order_Status: "In Transit",
      Delivery_Person: "David Lee",
      Order_Placed_Time: "2024-07-02T11:00:00",
      Order_delivery_time: "2024-11-02T12:30:00",
      Delivery_Status: "In Transit",
      Order_Date: "2024-10-11",
    },
    {
      Order_ID: 1003,
      Customer_Name: "Emily Brown",
      Customer_Phone: "555-9101",
      Customer_Address: "789 Pine St",
      Items: [
        {
          Item_Name: "California Roll",
          Item_Price: 12.99,
          Quantity: 3,
          Total_Price: 38.97,
        },
        {
          Item_Name: "Edamame",
          Item_Price: 4.99,
          Quantity: 1,
          Total_Price: 4.99,
        },
        {
          Item_Name: "Green Tea",
          Item_Price: 1.99,
          Quantity: 2,
          Total_Price: 3.98,
        },
      ],
      Order_Type: "Online",
      Order_Status: "Pending",
      Delivery_Person: "",
      Delivery_Status: "",
      Order_Placed_Time: "2024-08-03T11:00:00",
      Order_delivery_time: "2024-11-03T13:00:00",
      Order_Date: "2024-10-11",
    },
    {
      Order_ID: 1004,
      Customer_Name: "Michael Davis",
      Customer_Phone: "555-2468",
      Customer_Address: "246 Oak St",
      Items: [
        {
          Item_Name: "Margherita Pizza",
          Item_Price: 11.99,
          Quantity: 1,
          Total_Price: 11.99,
        },
        {
          Item_Name: "Caesar Salad",
          Item_Price: 7.99,
          Quantity: 1,
          Total_Price: 7.99,
        },
        {
          Item_Name: "Iced Tea",
          Item_Price: 2.49,
          Quantity: 2,
          Total_Price: 4.98,
        },
      ],
      Order_Type: "Dine In",
      Order_Status: "Delivered",
      Delivery_Person: "Emily Parker",
      Delivery_Status: "Delivered",
      Order_Placed_Time: "2024-02-04T11:00:00",
      Order_delivery_time: "2024-11-04T12:15:00",
      Order_Date: "2024-10-11",
    },
    {
      Order_ID: 1005,
      Customer_Name: "Sophia Wilson",
      Customer_Phone: "555-1357",
      Customer_Address: "357 Maple St",
      Items: [
        {
          Item_Name: "Chicken Tikka Masala",
          Item_Price: 13.99,
          Quantity: 2,
          Total_Price: 27.98,
        },
        {
          Item_Name: "Naan Bread",
          Item_Price: 3.49,
          Quantity: 3,
          Total_Price: 10.47,
        },
        {
          Item_Name: "Rice Pilaf",
          Item_Price: 4.99,
          Quantity: 2,
          Total_Price: 9.98,
        },
      ],
      Order_Type: "Online",
      Order_Status: "In Transit",
      Delivery_Person: "James Smith",
      Delivery_Status: "In Transit",
      Order_Placed_Time: "2024-01-09T11:00:00",
      Order_delivery_time: "2024-11-05T13:00:00",
      Order_Date: "2024-10-11",
    },
    {
      Order_ID: 1006,
      Customer_Name: "Emma Thompson",
      Customer_Phone: "555-3698",
      Customer_Address: "369 Pine St",
      Items: [
        {
          Item_Name: "Spaghetti Carbonara",
          Item_Price: 12.99,
          Quantity: 1,
          Total_Price: 12.99,
        },
        {
          Item_Name: "Garlic Bread",
          Item_Price: 5.99,
          Quantity: 2,
          Total_Price: 11.98,
        },
        {
          Item_Name: "Tiramisu",
          Item_Price: 6.99,
          Quantity: 1,
          Total_Price: 6.99,
        },
      ],
      Order_Type: "Dine In",
      Order_Status: "Delivered",
      Delivery_Person: "Sarah Johnson",
      Delivery_Status: "Delivered",
      Order_Placed_Time: "2024-11-06T11:00:00",
      Order_delivery_time: "2024-11-06T12:00:00",
      Order_Date: "2024-10-11",
    },
    {
      Order_ID: 1007,
      Customer_Name: "Oliver Brown",
      Customer_Phone: "555-2468",
      Customer_Address: "468 Oak St",
      Items: [
        {
          Item_Name: "Double Cheeseburger",
          Item_Price: 9.99,
          Quantity: 2,
          Total_Price: 19.98,
        },
        {
          Item_Name: "Onion Rings",
          Item_Price: 4.49,
          Quantity: 1,
          Total_Price: 4.49,
        },
        {
          Item_Name: "Soda",
          Item_Price: 1.99,
          Quantity: 3,
          Total_Price: 5.97,
        },
      ],
      Order_Type: "Online",
      Order_Status: "Delivered",
      Delivery_Person: "David Lee",
      Delivery_Status: "Delivered",
      Order_Placed_Time: "2024-11-07T11:00:00",
      Order_delivery_time: "2024-11-07T12:30:00",
      Order_Date: "2024-10-11",
    },
    {
      Order_ID: 1008,
      Customer_Name: "Isabella Garcia",
      Customer_Phone: "555-7890",
      Customer_Address: "789 Elm St",
      Items: [
        {
          Item_Name: "Fish and Chips",
          Item_Price: 14.99,
          Quantity: 1,
          Total_Price: 14.99,
        },
        {
          Item_Name: "Cole Slaw",
          Item_Price: 2.99,
          Quantity: 1,
          Total_Price: 2.99,
        },
        {
          Item_Name: "Lemonade",
          Item_Price: 2.49,
          Quantity: 1,
          Total_Price: 2.49,
        },
      ],
      Order_Type: "Dine In",
      Order_Status: "In Transit",
      Delivery_Person: "Emma Thompson",
      Delivery_Status: "In Transit",
      Order_Placed_Time: "2024-11-08T11:00:00",
      Order_delivery_time: "2024-11-08T12:15:00",
      Order_Date: "2024-10-11",
    },
    {
      Order_ID: 1009,
      Customer_Name: "Liam Martinez",
      Customer_Phone: "555-1357",
      Customer_Address: "135 Maple St",
      Items: [
        {
          Item_Name: "Pasta Primavera",
          Item_Price: 11.99,
          Quantity: 1,
          Total_Price: 11.99,
        },
        {
          Item_Name: "Caesar Salad",
          Item_Price: 5.99,
          Quantity: 1,
          Total_Price: 5.99,
        },
        {
          Item_Name: "Sparkling Water",
          Item_Price: 1.99,
          Quantity: 2,
          Total_Price: 3.98,
        },
      ],
      Order_Type: "Online",
      Order_Status: "Pending",
      Delivery_Person: "",
      Delivery_Status: "",
      Order_Placed_Time: "2024-11-09T11:00:00",
      Order_delivery_time: "2024-11-09T12:00:00",
      Order_Date: "2024-10-11",
    },
    {
      Order_ID: 1010,
      Customer_Name: "Charlotte Anderson",
      Customer_Phone: "555-6789",
      Customer_Address: "246 Cedar St",
      Items: [
        {
          Item_Name: "Shrimp Scampi",
          Item_Price: 18.99,
          Quantity: 1,
          Total_Price: 18.99,
        },
        {
          Item_Name: "Garlic Bread",
          Item_Price: 5.99,
          Quantity: 2,
          Total_Price: 11.98,
        },
        {
          Item_Name: "Ice Cream",
          Item_Price: 4.99,
          Quantity: 1,
          Total_Price: 4.99,
        },
      ],
      Order_Type: "Dine In",
      Order_Status: "In Transit",
      Delivery_Person: "Sarah Johnson",
      Delivery_Status: "In Transit",
      Order_Placed_Time: "2024-11-10T11:00:00",
      Order_delivery_time: "2024-11-10T12:00:00",
      Order_Date: "2024-10-11",
    },
  ];
  